#!/bin/bash

# Copyright (C) 1997 - 2014 devXive - research and development
#
# The scriptfile is licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# The content of static vars and/or static echo output is licensed under the
# devXive Proprietary Use License (http://devxive.com/legal/license)
#
# Author:  devXive, Lahmizzar Muinela
# Email:   support@devxive.com
# Twitter: @devxive
# Website: http://devxive.com
#
#
# Description:
# Simple script to pull tx translatons and build manifest files
# This script is to take control about what language will be pulled and stored in the language pack
# If you add a language, please have a look at the .tx/config file first and check if the language exists.
#
# This script is invoked by the create script

sourcePath=$(realpath .)

txClient="../../transifex-client/tx"
version="$1"

$txClient pull -l de_DE	# 100%
$sourcePath/builder/buildManifest de-DE de_DE $version

$txClient pull -l da_DK	# 95%
$sourcePath/builder/buildManifest da-DK da_DK $version

$txClient pull -l fr_FR	# 95%
$sourcePath/builder/buildManifest fr-FR fr_FR $version

$txClient pull -l hu_HU	# 95%
$sourcePath/builder/buildManifest hu-HU hu_HU $version

$txClient pull -l pt_BR	# 95%
$sourcePath/builder/buildManifest pt-BR pt_BR $version

$txClient pull -l es_ES	# 95%
$sourcePath/builder/buildManifest es-ES es_ES $version

$txClient pull -l tr_TR	# 95%
$sourcePath/builder/buildManifest tr-TR tr_TR $version

$txClient pull -l nb_NO	# 93%
$sourcePath/builder/buildManifest nb-NO nb_NO $version

$txClient pull -l pl_PL	# 93%
$sourcePath/builder/buildManifest pl-PL pl_PL $version

$txClient pull -l th_TH	# 93%
$sourcePath/builder/buildManifest th-TH th_TH $version

$txClient pull -l ca_ES	# 92%
$sourcePath/builder/buildManifest ca-ES ca_ES $version

$txClient pull -l zh_TW	# 92%
$sourcePath/builder/buildManifest zh-TW zh_TW $version

$txClient pull -l nl_NL	# 92%
$sourcePath/builder/buildManifest nl-NL nl_NL $version

$txClient pull -l it_IT	# 92%
$sourcePath/builder/buildManifest it-IT it_IT $version

$txClient pull -l ja_JP	# 92%
$sourcePath/builder/buildManifest ja-JP ja_JP $version

$txClient pull -l ro_RO	# 92%
$sourcePath/builder/buildManifest ro-RO ro_RO $version

$txClient pull -l ru_RU	# 91%
$sourcePath/builder/buildManifest ru-RU ru_RU $version

$txClient pull -l cs_CZ	# 89%
$sourcePath/builder/buildManifest cs-CZ cs_CZ $version

$txClient pull -l el_GR	# 89%
$sourcePath/builder/buildManifest el-GR el_GR $version

$txClient pull -l pt_PT	# 88%
$sourcePath/builder/buildManifest pt-PT pt_PT $version

$txClient pull -l sv_SE	# 86%
$sourcePath/builder/buildManifest sv-SE sv_SE $version

$txClient pull -l sk_SK	# 66%
$sourcePath/builder/buildManifest sk-SK sk_SK $version

$txClient pull -l uk_UA	# 54%
$sourcePath/builder/buildManifest uk-UA uk_UA $version

$txClient pull -l nl_BE	# 39%
$sourcePath/builder/buildManifest nl-BE nl_BE $version

$txClient pull -l fa_IR	# 33%
$sourcePath/builder/buildManifest fa-IR fa_IR $version

$txClient pull -l bg_BG	# 32%
$sourcePath/builder/buildManifest bg-BG bg_BG $version

$txClient pull -l es_MX	# 29%
$sourcePath/builder/buildManifest es-MX es_MX $version

$txClient pull -l ar_AA	# 22%
$sourcePath/builder/buildManifest ar-AA ar_AA $version
